### ISSUE TITLE
Fast-RTPS fails to build in Ubuntu 18.04

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-RTPS#376]
Hi there,

I am trying to build latest master on an Ubuntu 18.04 machine. I clone the repo recursively and use the following CMake config: `cmake -DTHIRDPARTY=ON -DBUILD_JAVA=ON ..`.
After issuing make, I get the following symlink errors:
```sh
CMakeFiles/fastrtps.dir/types/AnnotationParameterValue.cpp.o: In function `eprosima::fastrtps::types::AnnotationParameterValue::deserialize(eprosima::fastcdr::Cdr&)':
AnnotationParameterValue.cpp:(.text+0x2641): undefined reference to `eprosima::fastcdr::Cdr::readWString[abi:cxx11](unsigned int&)'
CMakeFiles/fastrtps.dir/types/AnnotationParameterValue.cpp.o: In function `eprosima::fastrtps::types::AnnotationParameterValue::serialize(eprosima::fastcdr::Cdr&) const':
AnnotationParameterValue.cpp:(.text+0x2426): undefined reference to `eprosima::fastcdr::Cdr::serialize(wchar_t const*)'
CMakeFiles/fastrtps.dir/types/DynamicData.cpp.o: In function `eprosima::fastrtps::types::DynamicData::SerializeEmptyData(eprosima::fastrtps::types::DynamicType_ptr, eprosima::fastcdr::Cdr&) const':
DynamicData.cpp:(.text+0x4903): undefined reference to `eprosima::fastcdr::Cdr::serialize(wchar_t const*)'
CMakeFiles/fastrtps.dir/types/DynamicData.cpp.o: In function `eprosima::fastrtps::types::DynamicData::serialize(eprosima::fastcdr::Cdr&) const':
DynamicData.cpp:(.text+0x4ccf): undefined reference to `eprosima::fastcdr::Cdr::serialize(wchar_t const*)'
CMakeFiles/fastrtps.dir/types/DynamicData.cpp.o: In function `eprosima::fastrtps::types::DynamicData::deserialize(eprosima::fastcdr::Cdr&)':
DynamicData.cpp:(.text+0xf43e): undefined reference to `eprosima::fastcdr::Cdr::readWString[abi:cxx11](unsigned int&)'
collect2: error: ld returned 1 exit status
src/cpp/CMakeFiles/fastrtps.dir/build.make:3423: recipe for target 'src/cpp/libfastrtps.so.1.7.0' failed
make[2]: *** [src/cpp/libfastrtps.so.1.7.0] Error 1
CMakeFiles/Makefile2:1083: recipe for target 'src/cpp/CMakeFiles/fastrtps.dir/all' failed
make[1]: *** [src/cpp/CMakeFiles/fastrtps.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```
A notice about my system: I have Fast-CDR 1.0.8 also installed from source and have both ROS2 Bouncy and Crystal installed on my system, though neither of them have their environments sourced.

The above also happens with the 1.7.0 release, though it builds correctly with 1.6.0.

**Comment by TSC21** [comment]
After sourcing the ROS2 Crystal env setup, it correctly builds. Closing.

**Comment by M4X404** [comment]
Hello TSC21,
I have the same problem. Can you please explain detailed what you did?
Thank you!

**Comment by TSC21** [comment]
@M4X404 the solution was unrelated to Fast-RTPS so I am not sure if this suits your problem. But what detail do you want? I just told above what I did :)

**Comment by M4X404** [comment]
I am operating on a system, where ROS2 is installed too. But I have no experience with ROS. So I dont now what you mean with:

> sourcing the ROS2 Crystal env setup

**Comment by M4X404** [comment]
So I mean, which file must be sourced and where is it located?
