### PR TITLE
Feature/pubsub layer changes [6448]

### PR DESCRIPTION
**Pull request by LuisGP**
This PR adds a new API to allow the implementation of TypeLookup Service  and implements Discovery-Time Data Typing.

* Minor changes in legacy API to allow being reused by the new one.
* "Fast-RTPS" code is moved to "fastrtps-deprecated" folder.
* RTPS code has its own folder.
* RTPS API is now under "fastdds" folder.
* Moved all public "Fast-RTPS" headers to "fastdds" and old locations now have a header that includes the new location to ease migration.
* Old examples and test should only have minor changes (mark methods as override, applying coding style, etc.).
* Added new tests and examples for the new functionallity.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/483/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/437/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/480/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/487/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/441/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/484/)

File: include/fastrtps/xmlparser/XMLProfileManager.h [hunk 1]
```diff
@@ -168,11 +168,13 @@ class XMLProfileManager
             m_xml_files.clear();
             m_transport_profiles.clear();
 
+            /*
             for (auto pair : m_dynamictypes)
             {
                 types::DynamicTypeBuilderFactory::get_instance()->delete_builder(pair.second);
             }
             m_dynamictypes.clear();
+            */
```
Comment (raquelalvarezbanos) [inline include/fastrtps/xmlparser/XMLProfileManager.h]: What's this and can it be removed if not needed?

File: src/cpp/fastrtps_deprecated/qos/ParameterList.cpp [hunk 2]
```diff
@@ -689,11 +689,16 @@ bool ParameterList::readParameterListfromCDRMsg(CDRMessage_t& msg, std::function
                         p.m_value.push_back(static_cast<DataRepresentationId_t>(temp));
 
                     }
+                    if (size % 2 == 1) // Odd, we must read the alignment
+                    {
+                        valid &= CDRMessage::readInt16(&msg, &temp);
+                        std::cout << "Leido odd: " << temp << std::endl;
```
Comment (raquelalvarezbanos) [inline src/cpp/fastrtps_deprecated/qos/ParameterList.cpp]: What's this change? And also changes below from `uint16_t` to `uint32_t`?

File: src/cpp/fastrtps_deprecated/types/TypeIdentifier.cpp [hunk 3]
```diff
@@ -1304,6 +1310,119 @@ bool TypeIdentifier::operator==(const TypeIdentifier &other) const
...
+        }
+        default:
+            break;
+    }
+    return false;
+}
+
 } // namespace types
 } // namespace fastrtps
 } // namespace eprosima
```
Comment (raquelalvarezbanos) [inline src/cpp/fastrtps_deprecated/types/TypeIdentifier.cpp]: Just realized that this file and some others above and below have been moved to `fastrtps_deprecated`, is that what we want? I thought we would have in that folder the current DDS API that we will eventually remove, but will we also remove classes in `types/`?

File: src/cpp/rtps/builtin/data/WriterProxyData.cpp [hunk 4]
```diff
@@ -65,9 +63,9 @@ WriterProxyData::WriterProxyData(const WriterProxyData& writerInfo)
     , m_typeMaxSerialized(writerInfo.m_typeMaxSerialized)
     , m_topicKind(writerInfo.m_topicKind)
     , persistence_guid_(writerInfo.persistence_guid_)
-    , m_topicDiscoveryKind(writerInfo.m_topicDiscoveryKind)
     , m_type_id(writerInfo.m_type_id)
     , m_type(writerInfo.m_type)
+    , m_type_information(writerInfo.m_type_information)
```
Comment (raquelalvarezbanos) [inline src/cpp/rtps/builtin/data/WriterProxyData.cpp]: These kind of changes were reviewed by @richiprosima , right?

File: src/cpp/rtps/builtin/discovery/participant/PDP.cpp [hunk 5]
```diff
@@ -818,6 +827,7 @@ WriterProxyData* PDP::addWriterProxyData(
                 WriterDiscoveryInfo info(*ret_val);
                 info.status = WriterDiscoveryInfo::DISCOVERED_WRITER;
                 listener->onWriterDiscovery(mp_RTPSParticipant->getUserRTPSParticipant(), std::move(info));
+                check_and_notify_type_discovery(listener, *ret_val);
```
Comment (raquelalvarezbanos) [inline src/cpp/rtps/builtin/discovery/participant/PDP.cpp]: Again, this kind of changes have been reviewed by @richiprosima , right?

**Comment by raquelalvarezbanos** [comment]
Some comments about my revision:

- I checked changes to example files and saw that they only had minor changes. So this is OK.
- Changes to header files under rtps only had minor changes, like head guards, indentation, etc. And those which had non-trivial changes were related to the new functionality being added, which I assume was reviewed by @richiprosima (please confirm this)
- I didn't review tests, as again, I assumed this was reviewed by @richiprosima?

File: CMakeLists.txt [hunk 6]
```diff
@@ -126,7 +126,8 @@ if(MSVC OR MSVC_IDE)
         string(REPLACE "/DNDEBUG" "" CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
     endif()
 else()
-    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -pedantic -Wextra -Wno-unknown-pragmas")
+    set(CMAKE_CXX_FLAGS
+        "${CMAKE_CXX_FLAGS} -Wall -pedantic -Wextra -Wno-unknown-pragmas -Wno-error=deprecated-declarations")
```
[the remark this answers is not in the document]
Comment (LuisGP) [reply CMakeLists.txt]: ``eClock.h`` header must be deprecated.

File: examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp [hunk 7]
```diff
@@ -0,0 +1,147 @@
...
+    std::cout << "Subscriber running. Please press enter to stop the Subscriber" << std::endl;
+    std::cin.ignore();
+}
+
+void HelloWorldSubscriber::run(uint32_t number)
+{
+    std::cout << "Subscriber running until "<< number << "samples have been received"<<std::endl;
+    while(number > this->m_listener.n_samples)
+        std::this_thread::sleep_for(std::chrono::milliseconds(500));
+}
```
[the remark this answers is not in the document]
Comment (LuisGP) [reply examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp]: Weird errors... I think these errors could be caused by colliding with other HelloWorld examples. I'm going to change the topic of this example.

File: test/unittest/transport/CMakeLists.txt [hunk 8]
```diff
@@ -184,7 +184,9 @@ if(NOT ((MSVC OR MSVC_IDE) AND EPROSIMA_INSTALLER))
             ${GTEST_INCLUDE_DIRS} ${GMOCK_INCLUDE_DIRS}
             ${PROJECT_SOURCE_DIR}/test/mock/rtps/MessageReceiver
             ${PROJECT_SOURCE_DIR}/test/mock/rtps/ReceiverResource
-            ${PROJECT_SOURCE_DIR}/include ${PROJECT_BINARY_DIR}/include)
+            ${PROJECT_SOURCE_DIR}/include ${PROJECT_BINARY_DIR}/include
+            ${PROJECT_SOURCE_DIR}/src/cpp
```
[the remark this answers is not in the document]
Comment (LuisGP) [reply test/unittest/transport/CMakeLists.txt]: Because now all `include` directives are with ``<>``, so unit tests need to added it.
The major improvement of this change is that we solve all mocking-occlusion problems.

File: include/fastdds/rtps/builtin/discovery/endpoint/EDP.h [hunk 9]
```diff
@@ -0,0 +1,269 @@
...
+                const WriterProxyData* wdata,
+                const ReaderProxyData* rdata) const;
+
+        bool checkTypeValidation(
+                const WriterProxyData* wdata,
+                const ReaderProxyData* rdata) const;
+
+        bool checkTypeIdentifier(
+                const WriterProxyData* wdata,
+                const ReaderProxyData* rdata) const;
```
[the remark this answers is not in the document]
Comment (LuisGP) [reply include/fastdds/rtps/builtin/discovery/endpoint/EDP.h]: Yes, that method is replaced by this one.

File: include/fastdds/rtps/common/Types.h [hunk 10]
```diff
@@ -0,0 +1,203 @@
...
+    READER,
+    WRITER
+}EndpointKind_t;
+
+//!Topic kind
+typedef enum TopicKind_t
+{
+    NO_KEY,
+    WITH_KEY
+}TopicKind_t;
```
[the remark this answers is not in the document]
Comment (LuisGP) [reply include/fastdds/rtps/common/Types.h]: Is not needed anymore.

File: include/fastdds/rtps/participant/RTPSParticipant.h [hunk 11]
```diff
@@ -0,0 +1,212 @@
...
+
+    //!Pointer to the implementation.
+    RTPSParticipantImpl* mp_impl;
+};
+
+}
+} /* namespace rtps */
+} /* namespace eprosima */
+
+#endif /* _FASTDDS_RTPS_RTPSParticipant_H_ */
```
[the remark this answers is not in the document]
Comment (LuisGP) [reply include/fastdds/rtps/participant/RTPSParticipant.h]: `get_new_entity_id` method allow us to get a new and unique `EntityId_t` for the `DDSPublisher` and `DDSSubscriber`. Previously, they shared its `EntityId_t` with their `RTPSReader`/`RTPSWriter`.

`set_check_type_function` is just a pass-throw method to configure the `check_type` function needed by `PDP` on type discovering (verifies if a type was already discovered).

File: include/fastdds/rtps/security/accesscontrol/ParticipantSecurityAttributes.h [hunk 12]
```diff
@@ -0,0 +1,137 @@
+// Copyright 2018 Proyectos y Sistemas de Ma#include <fastdds/rtps/security/common/Handle.h>ntenimiento SL (eProsima).
```
[the remark this answers is not in the document]
Comment (LuisGP) [reply include/fastdds/rtps/security/accesscontrol/ParticipantSecurityAttributes.h]: Seems a copy/paste issue. Removing.

File: include/fastrtps/participant/Participant.h [hunk 13]
```diff
@@ -78,28 +79,13 @@ class RTPS_DllAPI Participant
...
-                rtps::WriterProxyData& returnedInfo);
-        /**
-         * Retrieves remote reader information.
-         * @param readerGuid GUID of the reader.
-         * @param returnedInfo ReaderProxyData to be filled.
-         */
-        bool get_remote_reader_info(
-                const rtps::GUID_t& readerGuid,
-                rtps::ReaderProxyData& returnedInfo);
-
```
[the remark this answers is not in the document]
Comment (LuisGP) [reply include/fastrtps/participant/Participant.h]: I asked @MiguelCompany for this function, as it was used nowhere (if used by external tests or something).
We decided to remove it.

File: include/fastrtps/xmlparser/XMLProfileManager.h (hunk 1 above)
Comment (LuisGP) [reply include/fastrtps/xmlparser/XMLProfileManager.h]: At the beginning of times, the DynamicTypesFactory wasn't responsible for the types created by the XMLParser. These dark ages are gone for a long time ago. It is safe to remove, so I'll remove it.

File: src/cpp/fastrtps_deprecated/types/TypeIdentifier.cpp (hunk 3 above)
Comment (LuisGP) [reply src/cpp/fastrtps_deprecated/types/TypeIdentifier.cpp]: If I'm not wrong, we decided to apply the following changes to `src/cpp`:
* Move `fastrtps/rtps` to `rtps`
* Move `fastrtps` to `fastrtps_deprecated`.
* Add `fastdds` for the new API implementation.

File: src/cpp/fastrtps_deprecated/qos/ParameterList.cpp (hunk 2 above)
Comment (LuisGP) [reply src/cpp/fastrtps_deprecated/qos/ParameterList.cpp]: These changes were applied to fix serialization issues found by @richiware.

File: src/cpp/rtps/builtin/data/WriterProxyData.cpp (hunk 4 above)
Comment (LuisGP) [reply src/cpp/rtps/builtin/data/WriterProxyData.cpp]: Yes

File: src/cpp/rtps/builtin/discovery/participant/PDP.cpp (hunk 5 above)
Comment (LuisGP) [reply src/cpp/rtps/builtin/discovery/participant/PDP.cpp]: Yes.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/513/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/458/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/509/)

File: examples/C++/DDS/DynamicHelloWorldExample/HelloWorldPublisher.h [hunk 14]
```diff
@@ -0,0 +1,62 @@
...
+                eprosima::fastrtps::rtps::MatchingInfo& info) override;
+        int n_matched;
+        bool firstConnected;
+    }m_listener;
+    void runThread(uint32_t number, uint32_t sleep);
+};
+
+
+
+#endif /* HELLOWORLDPUBLISHER_H_ */
```
[the remark this answers is not in the document]
Comment (raquelalvarezbanos) [reply examples/C++/DDS/DynamicHelloWorldExample/HelloWorldPublisher.h]: Checked again and the seg fault is gone :+1:

File: examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (raquelalvarezbanos) [reply examples/C++/DDS/DynamicHelloWorldExample/HelloWorldSubscriber.cpp]: Checked again and it looks fine now:

Publisher:
```
Starting 
Publisher running 5 samples.
Publisher matched
Message: Hello DDS Dynamic World with index: 1 array: [[10, 60]], [20, 70]], [30, 80]], [40, 90]], [50, 100]] SENT
Message: Hello DDS Dynamic World with index: 2 array: [[11, 61]], [21, 71]], [31, 81]], [41, 91]], [51, 101]] SENT
Message: Hello DDS Dynamic World with index: 3 array: [[12, 62]], [22, 72]], [32, 82]], [42, 92]], [52, 102]] SENT
Message: Hello DDS Dynamic World with index: 4 array: [[13, 63]], [23, 73]], [33, 83]], [43, 93]], [53, 103]] SENT
Message: Hello DDS Dynamic World with index: 5 array: [[14, 64]], [24, 74]], [34, 84]], [44, 94]], [54, 104]] SENT
```

Subscriber:
```
Starting 
Subscriber running. Please press enter to stop the Subscriber
Discovered type: HelloWorld from topic DDSDynHelloWorldTopic
Subscriber matched
Received data of type HelloWorld
message: Hello DDS Dynamic World
index: 1
array: [10, 60, 20, 70, 30, 80, 40, 90, 50, 100]
Received data of type HelloWorld
message: Hello DDS Dynamic World
index: 2
array: [11, 61, 21, 71, 31, 81, 41, 91, 51, 101]
Received data of type HelloWorld
message: Hello DDS Dynamic World
index: 3
array: [12, 62, 22, 72, 32, 82, 42, 92, 52, 102]
Received data of type HelloWorld
message: Hello DDS Dynamic World
index: 4
array: [13, 63, 23, 73, 33, 83, 43, 93, 53, 103]
Received data of type HelloWorld
message: Hello DDS Dynamic World
index: 5
array: [14, 64, 24, 74, 34, 84, 44, 94, 54, 104]
Subscriber unmatched
```

File: include/fastrtps/participant/Participant.h (hunk 13 above)
[the remark this answers is not in the document]
Comment (raquelalvarezbanos) [reply include/fastrtps/participant/Participant.h]: :+1:

File: test/unittest/transport/CMakeLists.txt (hunk 8 above)
[the remark this answers is not in the document]
Comment (raquelalvarezbanos) [reply test/unittest/transport/CMakeLists.txt]: I thought the only difference between using quotes and brackets in the include directive was the location where the preprocessor searched for include files ¿?

[the remark this answers is not in the document]
Comment (LuisGP) [reply test/unittest/transport/CMakeLists.txt]: Exactly. Using quotes, the preprocessor starts the search in the current file's directory, and if fails, continues using the rest of include locations. That caused mocking occlusion because some source files were always including the real code instead of the mock.

File: CMakeLists.txt (hunk 6 above)
[the remark this answers is not in the document]
Comment (LuisGP) [reply CMakeLists.txt]: I see. `HelloWorld_main.cpp` includes the header, but doesn't use it. If you add `eClocl::my_sleep(100);`, for example, you'll get the warning message.

[the remark this answers is not in the document]
Comment (LuisGP) [reply CMakeLists.txt]: Removing the include.

File: test/unittest/transport/CMakeLists.txt (hunk 8 above)
[the remark this answers is not in the document]
Comment (raquelalvarezbanos) [reply test/unittest/transport/CMakeLists.txt]: Oh I see. OK, do a grep cause I just found some more places where `eClock` is being included, all in `examples/C++/DDS`

File: CMakeLists.txt (hunk 6 above)
[the remark this answers is not in the document]
Comment (raquelalvarezbanos) [reply CMakeLists.txt]: Oh I see. OK, do a grep cause I just found some more places where `eClock` is being included, all in `examples/C++/DDS`

[the remark this answers is not in the document]
Comment (raquelalvarezbanos) [reply CMakeLists.txt]: Thanks! Just re-checked and they are all gone now :)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/522/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/466/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/518/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/529/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/471/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/525/)

**Comment by cottsay** [comment]
Since merging this PR, all of our builds of `rmw_fastrtps*` are failing with messages like this:
```
In file included from src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp:24:0,
                 from src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/custom_subscriber_info.cpp:15:
install/fastrtps/include/fastrtps/subscriber/Subscriber.h:23:10: fatal error: fastdds/rtps/common/Guid.h: No such file or directory
 #include <fastdds/rtps/common/Guid.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

It looks like `fastrtps/subscriber/Subscriber.h` references `fastdds/rtps/common/Guid.h`. Should this file have been installed by Fast-RTPS?
