### ISSUE TITLE
Doesn't build with newer OpenSSL (as of Aug 25, 2016)

### ISSUE THREAD

**Issue by lshamis** [eProsima/Fast-RTPS#144]
Fast-RTPS does not build with openssl 1.1.0.
```
security/cryptography/AESGCMGMAC_KeyFactory.cpp:181:20: error: aggregate 'EVP_MD_CTX ctx' has incomplete type and cannot be defined
         EVP_MD_CTX ctx;

security/cryptography/AESGCMGMAC_KeyFactory.cpp:195:32: error: 'EVP_MD_CTX_cleanup' was not declared in this scope
         EVP_MD_CTX_cleanup(&ctx);
```

It looks like `EVP_MD_CTX_cleanup` was removed:
https://github.com/openssl/openssl/blob/OpenSSL_1_1_0/CHANGES#L492

**Comment by richiware** [comment]
Master branch was updated and now Fast RTPS compiles against OpenSSL 1.1.0. Thanks for the reporting.

**Comment by richiware** [comment]
I will close the issue.
